.TH GEMINI2HTML "1" "January 2022" "gemini2html v1.3.4"
.SH NAME
gemini2html \- convert gemini text to HTML
.SH SYNOPSIS
.B gemini2html
[\fIOPTION\fR]... < \fIinput.gmi \fR> \fIoutput.html
.SH DESCRIPTION
.B gemini2html
reads gemtext from standard input and writes the converted HTML to standard output.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Display the help menu.
.SH AUTHOR
Written by Nicholas Johnson.
.SH REPORTING BUGS
Report bugs to nick@nicholasjohnson.ch
.SH COPYRIGHT
Copyright © 2022 Nicholas Johnson. License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>. This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
